//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACOVIDWEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_donation
    {
        public int id { get; set; }
        public int tbl_user_id { get; set; }
        public Nullable<int> tbl_user_person { get; set; }
        public Nullable<int> tbl_category_donation_id { get; set; }
        public string description { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> fecha_assign { get; set; }
        public Nullable<System.DateTime> fecha_delivery { get; set; }
    
        public virtual tbl_category_donation tbl_category_donation { get; set; }
        public virtual tbl_user tbl_user { get; set; }
        public virtual tbl_user tbl_user1 { get; set; }
    }
}
